### ISSUE TITLE
Arquivo pom.xml

### ISSUE THREAD

**Issue by oliveiralex** [KellyCarvalho/ITTask#1]
Olá Kelly, tudo bem?
Meu nome é Alexandre e sou responsável por validar as atividades entregues neste capítulo.

Eu importei o seu trabalho para corrigir, no entanto o mesmo está faltando o arquivo pom.xml. Você criou ou projeto usando **file > new > spring starter project**?
Por gentileza, se você puder verificar e se possível fazer as adequações para que eu possa corrigir o seu trabalho, eu agradeço.

Abraço

**Comment by KellyCarvalho** [comment]
Olá tudo ótimo.
Na verdade eu clonei e implementei, mas iniciei o repositório após a pasta correta :( já corrigi
